# Scout94 CI/CD Pipeline
name: Scout94 Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, pdo, sqlite
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install chromium
    
    - name: Verify Scout94 installation
      run: |
        chmod +x scout94
        ./scout94 help
    
    - name: Run basic tests (without API keys)
      run: |
        # Test CLI functionality
        ./scout94 help
        
        # Verify core files exist
        test -f run_all_tests.php
        test -f run_with_audit.php
        test -f scout94_health_monitor.php
        test -f scout94_visual_tester.py
        
        echo "✅ Scout94 core files verified"
    
    - name: Test Python modules
      run: |
        python -c "import playwright; print('✅ Playwright OK')"
        python -c "import openai; print('✅ OpenAI OK')"
        python -c "from PIL import Image; print('✅ Pillow OK')"
        python -c "from dotenv import load_dotenv; print('✅ python-dotenv OK')"

  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Verify .env is not committed
      run: |
        if [ -f .env ]; then
          echo "❌ ERROR: .env file found in repository!"
          exit 1
        fi
        echo "✅ .env file correctly excluded"
    
    - name: Check for API keys in code
      run: |
        # Check for common API key patterns (excluding .env.example)
        if grep -r -i "GEMINI_API_KEY=AIza" --exclude=".env.example" --exclude-dir=".git" .; then
          echo "❌ ERROR: Possible Gemini API key found in code!"
          exit 1
        fi
        if grep -r -i "OPENAI_API_KEY=sk-" --exclude=".env.example" --exclude-dir=".git" .; then
          echo "❌ ERROR: Possible OpenAI API key found in code!"
          exit 1
        fi
        if grep -r -i "ANTHROPIC_API_KEY=sk-ant" --exclude=".env.example" --exclude-dir=".git" .; then
          echo "❌ ERROR: Possible Anthropic API key found in code!"
          exit 1
        fi
        echo "✅ No API keys found in code"
